# Tasks To Be Performed:
# 1. Create a script which can add text “This text has been added by custom
# script” to /tmp.1.txt
# 2. Run this script using Ansible on all the hosts

- name: addtext using ansible 
  hosts: all 
  become: yes
  tasks:
    - name: copy .sh file 
      copy:
        src: addtext.sh
        dest: /tmp/addtext.sh  
        mode: '777'
    - name: run copied .sh file 
      shell: /tmp/addtext.sh