# Tasks To Be Performed:
# 1. Create a new deployment of Ansible cluster of 5 nodes
# 2. Label 2 nodes as test and other 2 as prod
# 3. Install Java on test nodes
# 4. Install MySQL server on prod nodes
# Use Ansible roles for the above and group the hosts under test 

- name: installing java on test nodes 
  hosts: test 
  become: yes 
  roles: 
    - test 

- name: installing mysql on prod nodes 
  hosts: prod 
  become: yes 
  roles: 
    - prod 